version: '3.8'

networks:
  lambdaLogs:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
        
services:
  # Zookeeper for Kafka
  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper
    networks:
      lambdaLogs:
        ipv4_address: 172.18.0.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    ports:
      - "2181:2181"

  # Kafka Broker 1
  kafka-broker-1:
    image: bitnami/kafka
    container_name: kafka-broker-1
    depends_on:
      - zookeeper
    networks:
      lambdaLogs:
        ipv4_address: 172.18.0.3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    ports:
      - "9092:9092"

  # Kafka Broker 2
  kafka-broker-2:
    image: bitnami/kafka
    container_name: kafka-broker-2
    depends_on:
      - zookeeper
    networks:
      lambdaLogs:
        ipv4_address: 172.18.0.4
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-2:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
    ports:
      - "9093:9093"

  # Spark Master
  spark-master:
    image: bitnami/spark
    container_name: spark-master
    networks:
      lambdaLogs:
        ipv4_address: 172.18.0.5
    volumes:
      - ./consumers:/opt/bitnami/spark/consumers
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - "8080:8080"
      - "7077:7077"

  # Spark Worker 1
  spark-worker-1:
    image: bitnami/spark
    container_name: spark-worker-1
    networks:
      lambdaLogs:
        ipv4_address: 172.18.0.6
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8081
    depends_on:
      - spark-master
    ports:
      - "8081:8081"

  # Spark Worker 2
  spark-worker-2:
    image: bitnami/spark
    container_name: spark-worker-2
    networks:
      lambdaLogs:
        ipv4_address: 172.18.0.7
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8082
    depends_on:
      - spark-master
    ports:
      - "8082:8082"